name = "ACETestUtils"
uuid = "b973b150-f408-4aa5-b6a2-f0e33df46af3"
authors = ["Christoph Ortner <christophortner0@gmail.com> and contributors"]
version = "0.1.0-DEV"

[deps]
MLDataDevices = "7e8f7934-dd98-4c1a-8fe8-92b47a384d40"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
MLDataDevices = "1.9.3"
julia = "1.11, 1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
